CREATE PROCEDURE dbo.spValidateLogin
	@uname nvarchar(255),
	@userpw nvarchar(50)
AS
BEGIN TRY
	SET NOCOUNT ON
	BEGIN TRANSACTION
	
		IF EXISTS (SELECT TOP 1 ID From BugFarmUsers WHERE UNAME = @uname)
		BEGIN
			SELECT TOP 1 ID FROM BugFarmUsers
			WHERE (UNAME = @uname) AND (PasswordHash=HASHBYTES('SHA2_512', @userpw+CAST(Salt AS NVARCHAR(36))))
		END

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION;

	PRINT ERROR_MESSAGE();
END CATCH;